ExplodingEggs:
  Explosion:
    Enabled-By-Default: false
    Explosion-radius: 2
    Random-Explode: false
    Chance-For-Explosion: 40
  Damage:
    Block-Damage: true
  DisabledWorlds:
    - DisabledWorld1
    - DisabledWorld2