name: ExplodingEggs
main: pro.homiecraft.ExplodingEggs
version: 2.2
author: GudfareN
website: homiecraft.pro

commands:
   ee:
      description: Toggle explosion.
      permission: ExplodingEggs.ee
      usage: /ee
   explodingeggs:
      description: ExplodingEggs admin commands.
      permission: ExplodingEggs.admin
      usage: /explodingeggs