name: ExplodingEggs
main: src.com.ohneemc.ExplodingEggs
version: 2.3
author: GudfareN
website: homiecraft.pro

commands:
   ee:
      description: Toggle explosion.
      permission: ExplodingEggs.ee
      usage: /ee
   explodingeggs:
      description: ExplodingEggs admin commands.
      permission: ExplodingEggs.admin
      usage: /explodingeggs