name: ExplodingEggs
main: pro.homiecraft.ExplodingEggs
version: 2.1
author: GudfareN
website: homiecraft.pro

commands:
   ee:
      description: Toggle explosion.
      permission: ExplodingEggs.ee
      usage: /ee